[tools]
age = "1.3.1"
"http:exiftool" = { version = "13.59", bin = "exiftool", url = "https://github.com/exiftool/exiftool/archive/refs/tags/13.59.tar.gz", checksum = "sha256:87d3317882fdae9cb4dcfe57a96a378d0132ffc02c731315bf128b19ddcf7aac", size = 8653399, strip_components = "1" }
minisign = "0.12"
python = "3.12.3"
rclone = "1.75.0"
uv = "0.11.24"

[settings]
http_retries = 5
lockfile = true
