version = 1

[[annotations]]
path = "**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Nash Spence"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "riverhog/**",
  "some-implementations/riverhog/storage/aws/**",
  "some-implementations/riverhog/storage/backblaze/**",
  "some-implementations/riverhog/storage/filesystem/**",
  "some-implementations/riverhog/ingress/ftp/**",
  "some-implementations/riverhog/applications/a-riverhog-minisign-witness/**",
  "some-implementations/riverhog/applications/a-riverhog-opentimestamps-witness/**",
  "some-implementations/stove0/application/server/**",
  "some-implementations/stove0/observers/exiftool/**",
  "some-implementations/stove0/observers/ffprobe-sampling/**",
  "some-implementations/stove0/targets/nvenc-av1-opus/**",
  "some-implementations/stove0/targets/opus/**",
  "some-implementations/stove0/review0/**",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Nash Spence"
SPDX-License-Identifier = "CAL-1.0"

[[annotations]]
path = [
  "riverhog/openapi/**",
  "some-implementations/stove0/review0/contracts/**",
  "some-implementations/stove0/review0/planning/**",
  "some-implementations/stove0/review0/sampler/client/**",
  "some-implementations/stove0/review0/sampler/protocol/**",
  "some-implementations/stove0/review0/sampler/support/**",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Nash Spence"
SPDX-License-Identifier = "Apache-2.0"
