version = 1

[[annotations]]
path = "**"
precedence = "override"
SPDX-FileCopyrightText = "2026 Nash Spence"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "riverhog/server/**",
  "reference/riverhog/storage/aws/**",
  "reference/riverhog/storage/backblaze/**",
  "reference/riverhog/storage/filesystem/**",
  "companions/stove0/server/**",
  "reference/stove0/observers/exiftool/**",
  "reference/stove0/observers/ffprobe-sampling/**",
  "reference/stove0/targets/nvenc-av1-opus/**",
  "reference/stove0/targets/opus/**",
  "reference/stove0/targets/review/**",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Nash Spence"
SPDX-License-Identifier = "CAL-1.0"

[[annotations]]
path = [
  "riverhog/server/openapi/**",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 Nash Spence"
SPDX-License-Identifier = "Apache-2.0"
