"""Protocol-owned error acceptance for Riverhog HTTP operations."""

from __future__ import annotations

from http_api_contracts import HttpOperationErrorAuthority

RIVERHOG_HTTP_ERROR_AUTHORITY = HttpOperationErrorAuthority.from_codes(
    common=("bad_request", "unauthorized", "forbidden", "internal_error"),
    operation={
        "create_catalog_sync_checkpoint": (),
        "list_catalog_sync_collections": (
            "catalog_sync_cursor_expired",
            "catalog_sync_history_expired",
            "catalog_sync_source_changed",
            "catalog_sync_view_changed",
        ),
        "list_catalog_sync_changes": (
            "catalog_sync_cursor_expired",
            "catalog_sync_history_expired",
            "catalog_sync_source_changed",
            "catalog_sync_view_changed",
        ),
        "create_or_resume_collection_upload_session": ("conflict",),
        "register_collection_upload_session_files": ("conflict", "not_found"),
        "create_collection_upload_session_provenance_journal": ("conflict", "not_found"),
        "append_collection_upload_session_provenance_journal": (
            "conflict",
            "length_required",
            "not_found",
        ),
        "seal_collection_upload_session_provenance_journal": ("conflict", "not_found"),
        "get_collection_upload_session_provenance_journal": ("not_found",),
        "list_collection_upload_session_files": ("not_found",),
        "complete_collection_upload_session": ("conflict", "not_found"),
        "cancel_collection_upload_session": ("conflict", "not_found"),
        "get_collection_upload_session": ("not_found",),
        "acquire_collection_upload_session_work": ("not_found",),
        "get_collection_upload_session_unit": ("not_found",),
        "put_collection_upload_session_unit": ("conflict", "length_required", "not_found"),
        "get_collection": ("not_found",),
        "plan_collection_deletion": ("conflict", "invalid_state", "not_found"),
        "delete_collection": ("conflict", "invalid_state", "not_found"),
        "create_or_resume_archive_copy": ("conflict", "invalid_state", "not_found"),
        "cancel_archive_copy_job": ("invalid_state", "not_found"),
        "get_archive_copy_job": ("not_found",),
        "plan_archive_copy_retirement": ("invalid_state", "not_found"),
        "retire_archive_copy": (
            "conflict",
            "invalid_state",
            "not_found",
            "service_unavailable",
        ),
        "get_archive_store": ("not_found",),
        "get_retrieval_cache_object": ("not_found",),
        "plan_retrieval": ("conflict", "not_found"),
        "get_retrieval_plan": ("not_found",),
        "advance_retrieval_plan": ("not_found",),
        "list_retrieval_plan_files": ("invalid_state", "not_found", "precondition_failed"),
        "create_retrieval_job": (
            "conflict",
            "download_allowance_exceeded",
            "invalid_state",
            "not_found",
        ),
        "renew_retrieval_job": ("invalid_state", "not_found"),
        "get_retrieval_job": ("not_found",),
        "cancel_retrieval_job": ("invalid_state", "not_found"),
        "acknowledge_retrieval_job": ("invalid_state", "not_found"),
        "download_retrieval_file": (
            "download_allowance_exceeded",
            "invalid_range",
            "invalid_state",
            "not_found",
            "precondition_failed",
        ),
        "get_download_quota": ("download_allowance_exceeded", "not_found"),
        "set_app_key_download_quota": ("download_allowance_exceeded", "not_found"),
        "list_collection_tags": ("conflict", "not_found"),
        "collection_contains_tag": ("conflict", "not_found"),
        "add_collection_tag": ("conflict", "not_found", "precondition_failed"),
        "remove_collection_tag": ("conflict", "not_found", "precondition_failed"),
        "create_app_key": ("not_found",),
        "rotate_app_key": ("not_found",),
        "replace_app_key_access": ("not_found",),
        "add_app_key_access": ("conflict", "not_found"),
        "remove_app_key_access": ("not_found",),
        "revoke_app_key": ("not_found",),
        "list_collection_provenance": ("invalid_state", "not_found"),
        "get_collection_file_provenance": ("invalid_state", "not_found"),
        "trace_collection_file_provenance": ("invalid_state", "not_found"),
        "stream_collection_provenance_journal": (
            "not_found",
            "precondition_failed",
            "precondition_required",
        ),
        "list_collection_provenance_journal_agents": ("not_found",),
        "request_collection_provenance_verification": ("not_found",),
        "get_collection_provenance_verification": ("not_found",),
        "cancel_collection_provenance_verification": ("not_found",),
        "get_portable_collection_inventory": (
            "not_found",
            "precondition_failed",
            "precondition_required",
        ),
        "create_or_resume_processing_claim": ("conflict", "invalid_state", "not_found"),
        "list_processing_claims": ("invalid_state",),
        "get_processing_claim": ("invalid_state", "not_found"),
        "renew_processing_claim": ("conflict", "invalid_state", "not_found"),
        "restart_processing_claim": ("conflict", "invalid_state", "not_found"),
        "abandon_processing_claim": ("conflict", "invalid_state", "not_found"),
        "seal_processing_claim_plan": ("conflict", "invalid_state", "not_found"),
        "create_transform_capability": ("conflict", "invalid_state", "not_found"),
        "record_processing_claim_dispositions": ("conflict", "invalid_state", "not_found"),
        "list_processing_claim_dispositions": ("conflict", "not_found"),
        "record_processing_claim_disposition_outputs": (
            "conflict",
            "invalid_state",
            "not_found",
        ),
        "list_processing_claim_disposition_outputs": ("conflict", "not_found"),
        "seal_processing_claim_dispositions": ("conflict", "invalid_state", "not_found"),
        "get_processing_claim_dispositions": ("not_found",),
        "settle_processing_claim": ("conflict", "invalid_state", "not_found"),
        "settle_processing_claim_outcomes": ("conflict", "invalid_state", "not_found"),
        "begin_processing_claim_retirement": ("conflict", "invalid_state", "not_found"),
        "release_processing_claim": ("conflict", "invalid_state", "not_found"),
        "get_collection_derivation": ("not_found",),
    },
    exact={
        "health_live": ("internal_error",),
        "health_ready": ("internal_error", "service_unavailable"),
    },
)


__all__ = ["RIVERHOG_HTTP_ERROR_AUTHORITY"]
