"""Bounded API transport batches that do not limit domain cardinality."""

COLLECTION_UPLOAD_FILE_BATCH_MAX = 100
COLLECTION_UPLOAD_WORK_BATCH_MAX = 64
COLLECTION_UPLOAD_PROVENANCE_APPEND_BYTES_MAX = 1024 * 1024
COLLECTION_UPLOAD_UNIT_SOURCE_MAX = 1000
RETRIEVAL_FILE_BATCH_MAX = 10_000

__all__ = [
    "COLLECTION_UPLOAD_FILE_BATCH_MAX",
    "COLLECTION_UPLOAD_UNIT_SOURCE_MAX",
    "COLLECTION_UPLOAD_WORK_BATCH_MAX",
    "RETRIEVAL_FILE_BATCH_MAX",
]
