"""Dependency-light public models for external stove0 targets."""

from http_api_contracts import (
    HttpErrorContract,
    HttpOperationContract,
    HttpPathParameterContract,
)
from stove0_protocol import (
    JSON_SCHEMA_ONLY_SEMANTIC_PROFILE,
    SemanticValidationProfile,
    SemanticValidationProfilePayload,
)

from stove0_target_protocol.conformance import (
    SemanticIntentConformanceVector,
    SemanticIntentConformanceVectors,
)
from stove0_target_protocol.jcs import canonical_json_bytes, canonical_json_sha256
from stove0_target_protocol.protocol import (
    ARTIFACT_ID_PATTERN,
    EFFECT_RECEIPT_FORMAT,
    EFFECT_TARGET_PROTOCOL,
    SHA256_PATTERN,
    TARGET_INPUT_PAGE_MAX,
    TRANSFORM_TARGET_PROTOCOL,
    AcceptedTargetJob,
    EffectPlan,
    EffectPlanPayload,
    ExternalEffectReceipt,
    ExternalEffectReceiptPayload,
    InputArtifact,
    InputArtifactContract,
    InputDisposition,
    InputDispositionDeclaration,
    OperationContract,
    OperationContractPayload,
    OutputArtifact,
    OutputArtifactContract,
    OutputArtifactRoleCount,
    OutputArtifactSetIdentity,
    OutputCollectionRef,
    OutputSourceEdge,
    SemanticId,
    Sha256,
    TargetCallbackAccess,
    TargetCallbackAcknowledgement,
    TargetContract,
    TargetContractPayload,
    TargetDeclaration,
    TargetExecutionEvidence,
    TargetFailure,
    TargetInapplicable,
    TargetInputAuthority,
    TargetInputPage,
    TargetInputRoleCount,
    TargetJobDeclaration,
    TargetJobRequest,
    TargetJobState,
    TargetJobStatus,
    TargetOperationSupport,
    TargetOutputBinding,
    TargetOutputBindingSetIdentity,
    TargetPlan,
    TargetPreflightRequest,
    TargetPreflightResponse,
    TargetProductionAuthority,
    TargetProductionAuthorityPayload,
    TargetProductionSealResponse,
    TargetProgress,
    TargetProtocol,
    TargetProtocolModel,
    TargetResultKind,
    TargetRuntimeAuthority,
    TargetSettlementAuthority,
    TargetSettlementAuthorityPayload,
    TransformPlan,
    TransformPlanPayload,
    WorkspaceAssurance,
    update_input_disposition_commitment,
    update_output_artifact_commitment,
    update_output_source_edge_commitment,
    update_target_output_binding_commitment,
    validate_declaration_against_operation,
    validate_preflight_response_against_request,
    validate_status_against_request,
)

_TARGET_HTTP_ERROR_STATUS: dict[str, int] = {
    "bad_request": 400,
    "invalid_target_request": 400,
    "job_identity_mismatch": 409,
    "job_not_found": 404,
    "job_request_mismatch": 409,
    "operation_contract_mismatch": 409,
    "request_too_large": 413,
    "target_contract_mismatch": 409,
    "target_failed": 500,
    "target_protocol_mismatch": 409,
    "target_runtime_mismatch": 409,
    "unauthorized": 401,
    "unsupported_operation": 400,
}


def _target_http_errors(*codes: str) -> tuple[HttpErrorContract, ...]:
    return tuple(HttpErrorContract(code, _TARGET_HTTP_ERROR_STATUS[code]) for code in codes)


_JOB_ID_PARAMETER = (HttpPathParameterContract("job_id", Sha256),)
TARGET_HTTP_OPERATIONS = (
    HttpOperationContract(
        "GET",
        "/v1/target",
        response_type=TargetContract,
        errors=_target_http_errors("bad_request", "unauthorized", "target_failed"),
    ),
    HttpOperationContract(
        "POST",
        "/v1/preflight",
        TargetPreflightRequest,
        TargetPreflightResponse,
        "json",
        errors=_target_http_errors(
            "invalid_target_request",
            "unauthorized",
            "request_too_large",
            "target_protocol_mismatch",
            "operation_contract_mismatch",
            "unsupported_operation",
            "target_failed",
        ),
    ),
    HttpOperationContract(
        "PUT",
        "/v1/jobs/{job_id}",
        TargetJobRequest,
        TargetJobStatus,
        "json",
        errors=_target_http_errors(
            "invalid_target_request",
            "unauthorized",
            "request_too_large",
            "job_identity_mismatch",
            "target_contract_mismatch",
            "operation_contract_mismatch",
            "job_request_mismatch",
            "target_runtime_mismatch",
            "unsupported_operation",
            "target_failed",
        ),
        path_parameters=_JOB_ID_PARAMETER,
    ),
    HttpOperationContract(
        "GET",
        "/v1/jobs/{job_id}",
        response_type=TargetJobStatus,
        errors=_target_http_errors("bad_request", "unauthorized", "job_not_found", "target_failed"),
        path_parameters=_JOB_ID_PARAMETER,
    ),
    HttpOperationContract(
        "POST",
        "/v1/jobs/{job_id}/cancel",
        response_type=TargetJobStatus,
        errors=_target_http_errors("bad_request", "unauthorized", "job_not_found", "target_failed"),
        path_parameters=_JOB_ID_PARAMETER,
    ),
)

_CALLBACK_ERRORS = _target_http_errors(
    "bad_request",
    "unauthorized",
    "job_not_found",
    "job_request_mismatch",
    "target_failed",
)
TARGET_CALLBACK_HTTP_OPERATIONS = (
    HttpOperationContract(
        "GET",
        "/v1/target-executions/{job_id}/inputs",
        response_type=TargetInputPage,
        errors=_CALLBACK_ERRORS,
        path_parameters=_JOB_ID_PARAMETER,
    ),
    HttpOperationContract(
        "PUT",
        "/v1/target-executions/{job_id}/outputs/{artifact_id}",
        OutputArtifact,
        TargetCallbackAcknowledgement,
        "json",
        errors=_CALLBACK_ERRORS,
        path_parameters=(
            HttpPathParameterContract("job_id", Sha256),
            HttpPathParameterContract("artifact_id", str),
        ),
    ),
    HttpOperationContract(
        "PUT",
        "/v1/target-executions/{job_id}/dispositions/{input_id}",
        InputDispositionDeclaration,
        TargetCallbackAcknowledgement,
        "json",
        errors=_CALLBACK_ERRORS,
        path_parameters=(
            HttpPathParameterContract("job_id", Sha256),
            HttpPathParameterContract("input_id", str),
        ),
    ),
    HttpOperationContract(
        "PUT",
        "/v1/target-executions/{job_id}/source-edges/{output_id}/{input_id}",
        OutputSourceEdge,
        TargetCallbackAcknowledgement,
        "json",
        errors=_CALLBACK_ERRORS,
        path_parameters=(
            HttpPathParameterContract("job_id", Sha256),
            HttpPathParameterContract("output_id", str),
            HttpPathParameterContract("input_id", str),
        ),
    ),
    HttpOperationContract(
        "POST",
        "/v1/target-executions/{job_id}/production/seal",
        response_type=TargetProductionSealResponse,
        errors=_CALLBACK_ERRORS,
        path_parameters=_JOB_ID_PARAMETER,
    ),
)

__all__ = [
    "AcceptedTargetJob",
    "ARTIFACT_ID_PATTERN",
    "SHA256_PATTERN",
    "TARGET_INPUT_PAGE_MAX",
    "EFFECT_RECEIPT_FORMAT",
    "EFFECT_TARGET_PROTOCOL",
    "TRANSFORM_TARGET_PROTOCOL",
    "EffectPlan",
    "EffectPlanPayload",
    "ExternalEffectReceipt",
    "ExternalEffectReceiptPayload",
    "InputArtifact",
    "InputDisposition",
    "InputArtifactContract",
    "InputDispositionDeclaration",
    "JSON_SCHEMA_ONLY_SEMANTIC_PROFILE",
    "OperationContract",
    "OperationContractPayload",
    "OutputArtifact",
    "OutputArtifactContract",
    "OutputArtifactRoleCount",
    "OutputArtifactSetIdentity",
    "OutputCollectionRef",
    "OutputSourceEdge",
    "SemanticId",
    "SemanticIntentConformanceVector",
    "SemanticIntentConformanceVectors",
    "SemanticValidationProfile",
    "SemanticValidationProfilePayload",
    "Sha256",
    "TargetContract",
    "TARGET_HTTP_OPERATIONS",
    "TARGET_CALLBACK_HTTP_OPERATIONS",
    "TargetContractPayload",
    "TargetExecutionEvidence",
    "TargetFailure",
    "TargetInapplicable",
    "TargetCallbackAccess",
    "TargetCallbackAcknowledgement",
    "TargetInputAuthority",
    "TargetInputPage",
    "TargetInputRoleCount",
    "TargetJobDeclaration",
    "TargetJobRequest",
    "TargetJobState",
    "TargetJobStatus",
    "TargetOperationSupport",
    "TargetOutputBinding",
    "TargetOutputBindingSetIdentity",
    "TargetPlan",
    "TargetPreflightRequest",
    "TargetPreflightResponse",
    "TargetProgress",
    "TargetProductionAuthority",
    "TargetProductionAuthorityPayload",
    "TargetProductionSealResponse",
    "TargetProtocolModel",
    "TargetProtocol",
    "TargetResultKind",
    "TargetRuntimeAuthority",
    "TargetSettlementAuthority",
    "TargetSettlementAuthorityPayload",
    "TargetDeclaration",
    "TransformPlan",
    "TransformPlanPayload",
    "WorkspaceAssurance",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "validate_declaration_against_operation",
    "validate_preflight_response_against_request",
    "validate_status_against_request",
    "update_output_artifact_commitment",
    "update_input_disposition_commitment",
    "update_output_source_edge_commitment",
    "update_target_output_binding_commitment",
]
