"""Immutable DDL snapshot for the current Riverhog CLI local-state v1 baseline."""

# ruff: noqa: E501

# This module is migration authority. Runtime model metadata must never be imported here.

SQLITE_DDL: tuple[str, ...] = (
    "CREATE TABLE desired_collections (\n\tcollection_id INTEGER NOT NULL, \n\tarchive_root_sha256 TEXT NOT NULL, \n\tinventory_identity TEXT NOT NULL, \n\tartifact_set_identity TEXT NOT NULL, \n\tprovenance_identity TEXT NOT NULL, \n\tcreated_at TEXT NOT NULL, \n\tlayout_mode TEXT NOT NULL, \n\trules_json TEXT NOT NULL, \n\tremote_unavailable INTEGER DEFAULT 0 NOT NULL, \n\tPRIMARY KEY (collection_id), \n\tCONSTRAINT ck_desired_collections_id CHECK (collection_id > 0), \n\tCONSTRAINT ck_desired_collections_layout CHECK (layout_mode IN ('declared-hints', 'id-layout')), \n\tCONSTRAINT ck_desired_collections_unavailable CHECK (remote_unavailable IN (0, 1))\n)",
    "CREATE TABLE retrieval_jobs (\n\tid TEXT NOT NULL, \n\tstate TEXT NOT NULL, \n\tupdated_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_retrieval_jobs_state CHECK (state IN ('requested', 'ready', 'completed', 'expired', 'failed', 'canceled'))\n)",
    'CREATE TABLE settings (\n\t"key" TEXT NOT NULL, \n\tvalue TEXT NOT NULL, \n\tPRIMARY KEY ("key")\n)',
    "CREATE TABLE desired_artifacts (\n\tcollection_id INTEGER NOT NULL, \n\tartifact_id TEXT NOT NULL, \n\tbytes INTEGER NOT NULL, \n\tsha256 TEXT NOT NULL, \n\tdestination_json TEXT NOT NULL, \n\treason TEXT NOT NULL, \n\thint_json TEXT, \n\tbinding_json TEXT NOT NULL, \n\tprimary_bytes INTEGER NOT NULL, \n\tprimary_sha256 TEXT NOT NULL, \n\thistory_binding_json TEXT NOT NULL, \n\thistory_extent TEXT NOT NULL, \n\thistory_proof_json TEXT NOT NULL, \n\tPRIMARY KEY (collection_id, artifact_id), \n\tCONSTRAINT ck_desired_artifacts_bytes CHECK (bytes >= 0), \n\tCONSTRAINT ck_desired_artifacts_primary_bytes CHECK (primary_bytes > 0), \n\tCONSTRAINT ck_desired_artifacts_history_extent CHECK (history_extent = 'complete-retained-history'), \n\tCONSTRAINT uq_desired_artifact_destination UNIQUE (collection_id, destination_json), \n\tFOREIGN KEY(collection_id) REFERENCES desired_collections (collection_id) ON DELETE CASCADE\n)",
    "CREATE TABLE desired_collection_tags (\n\tcollection_id INTEGER NOT NULL, \n\ttag TEXT NOT NULL, \n\tPRIMARY KEY (collection_id, tag), \n\tFOREIGN KEY(collection_id) REFERENCES desired_collections (collection_id) ON DELETE CASCADE\n)",
    "CREATE TABLE desired_history_objects (\n\tcollection_id INTEGER NOT NULL, \n\tobject_id TEXT NOT NULL, \n\tbytes INTEGER NOT NULL, \n\tsha256 TEXT NOT NULL, \n\tPRIMARY KEY (collection_id, object_id), \n\tCONSTRAINT ck_desired_history_objects_bytes CHECK (bytes > 0), \n\tFOREIGN KEY(collection_id) REFERENCES desired_collections (collection_id) ON DELETE CASCADE\n)",
    "CREATE TABLE desired_journals (\n\tcollection_id INTEGER NOT NULL, \n\tjournal_id TEXT NOT NULL, \n\tbytes INTEGER NOT NULL, \n\tsha256 TEXT NOT NULL, \n\tPRIMARY KEY (collection_id, journal_id), \n\tCONSTRAINT ck_desired_journals_bytes CHECK (bytes > 0), \n\tFOREIGN KEY(collection_id) REFERENCES desired_collections (collection_id) ON DELETE CASCADE\n)",
    "CREATE TABLE retrieval_job_artifacts (\n\tretrieval_job_id TEXT NOT NULL, \n\tordinal INTEGER NOT NULL, \n\tcollection_id INTEGER NOT NULL, \n\tartifact_id TEXT NOT NULL, \n\tbytes INTEGER NOT NULL, \n\tsha256 TEXT NOT NULL, \n\tPRIMARY KEY (retrieval_job_id, ordinal), \n\tCONSTRAINT ck_retrieval_job_artifacts_ordinal CHECK (ordinal >= 0), \n\tCONSTRAINT ck_retrieval_job_artifacts_collection CHECK (collection_id > 0), \n\tCONSTRAINT ck_retrieval_job_artifacts_bytes CHECK (bytes >= 0), \n\tCONSTRAINT uq_retrieval_job_artifacts_member UNIQUE (retrieval_job_id, collection_id, artifact_id), \n\tFOREIGN KEY(retrieval_job_id) REFERENCES retrieval_jobs (id) ON DELETE CASCADE\n)",
)
