metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "garage:3901"
rpc_secret = "70fc0ac8a1afa341cfed976b75714b0d6cfc6a5e62ee5bf10599fda61a6fd8f2"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "bh8X2S9sHGJOVG2wS-IGYq-9-U1aVvWk"
metrics_token = "nq2Akf2n24JT8YlyVFBnCYnLwc4wKjqJ"
