from __future__ import annotations

import hashlib
import inspect
import re
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any, cast
from urllib.parse import unquote

import piggity.main
import pytest
from riverhog_api.routers import collections as collection_routes
from riverhog_client import ApiClient

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))

import contract_atlas as atlas  # noqa: E402
from contract_atlas import discovery, dossier_rendering, navigation  # noqa: E402

ARTIFACT = REPO_ROOT / "qualification/contracts/riverhog-v1.json"
_CHECKED_ATLAS: atlas.ContractAtlas | None = None


@pytest.fixture(scope="module", autouse=True)
def _bind_checked_atlas(checked_contract_closure: dict[str, Any]) -> None:
    global _CHECKED_ATLAS
    _CHECKED_ATLAS = cast(atlas.ContractAtlas, checked_contract_closure["atlas"])


def checked_atlas() -> atlas.ContractAtlas:
    """Return the session-validated immutable closure for presentation assertions."""

    assert _CHECKED_ATLAS is not None
    return _CHECKED_ATLAS


def test_atlas_rollups_and_dossiers_are_exact_and_descriptive() -> None:
    checked = checked_atlas()
    root = checked.root
    elements = root["elements"]
    documents = root["atlas"]["documents"]
    dossier_documents = [item for item in documents if item["kind"] == "dossier"]

    assert len(dossier_documents) == len(elements) == root["counts"]["contract_elements"]
    assert root["counts"]["extent_decisions"] == len(
        root["projection"]["external_contract"]["extents"]["decisions"]
    )
    assert sum(root["counts"]["by_authority"].values()) == len(elements)
    assert sum(root["counts"]["by_interface"].values()) == len(elements)
    assert all(item["path"].endswith(".md") for item in documents)
    assert all("/contexts/" not in item["path"] for item in documents)
    assert all("/traces/" not in item["path"] for item in documents)
    assert all(not Path(item["path"]).name.startswith("c-") for item in dossier_documents)
    assert checked.files[root["atlas"]["root"]].startswith(
        b"# Riverhog repository v1 contract audit\n"
    )
    assert hashlib.sha256(checked.files[root["atlas"]["root"]]).hexdigest() == next(
        item["sha256"] for item in documents if item["kind"] == "root-index"
    )
    # Presentation-quality witness, deliberately outside machine-closure validation.
    # Link destinations are navigation syntax, not additional visible reading content.
    # Exact destinations and their source associations have independent checks below.
    assert max(
        len(re.sub(rb"\]\([^\s)]+\)", b"]", payload.split(b"### Exact owned JSON", 1)[0]))
        for payload in checked.files.values()
    ) <= (atlas.AUDIT_PRIMARY_CONTENT_TARGET_BYTES)
    assert all(b"### Exact owned JSON" in checked.files[item["dossier"]] for item in elements)


def test_durable_state_and_python_structures_are_exact_human_audit_units() -> None:
    checked = checked_atlas()
    projection = checked.root["projection"]
    elements = checked.root["elements"]
    state_owners = projection["external_contract"]["durable_state"]["owners"]
    state_elements = [item for item in elements if item["interface"] == "durable-state"]
    expected_units = 0
    for owner in state_owners:
        structure = owner["structure"]
        collections = [value for value in structure.values() if isinstance(value, list)]
        expected_units += 1 + sum(len(value) for value in collections)
    assert len(state_elements) == expected_units
    assert all("state_unit" in item["details"] for item in state_elements)

    collections = next(
        item
        for item in state_elements
        if item["authority"] == "riverhog-catalog" and item["title"].endswith(": collections")
    )
    collections_page = checked.files[collections["dossier"]].decode()
    assert "#### Columns" in collections_page
    assert "#### Table constraints" in collections_page
    assert "`description_search`" in collections_page
    assert "`ck_collections_archive_root_sha256`" in collections_page

    uploads = next(
        item
        for item in state_elements
        if item["authority"] == "riverhog-catalog"
        and item["title"].endswith(": collection_uploads")
    )
    uploads_primary = checked.files[uploads["dossier"]].decode().split("### Exact owned JSON")[0]
    assert (
        '`collection_id` | `BIGINT` | no | `—` | {"generated":"GENERATED BY DEFAULT AS IDENTITY"} |'
    ) in uploads_primary

    pydantic_element = next(
        item
        for item in elements
        if item["interface"] == "python"
        and "schema" in atlas.pointer_value(projection, item["pointers"][0])["contract"]
    )
    pydantic_page = checked.files[pydantic_element["dossier"]].decode()
    assert "#### Validated model schema" in pydantic_page
    assert "##### Fields" in pydantic_page

    sources_page = checked.files["riverhog-v1/evidence/sources.md"].decode()
    assert "tests/fixtures/state/v1_0001/riverhog.postgresql.sql" in sources_page


def test_http_semantics_are_owned_once_and_operation_bindings_remain_structural() -> None:
    checked = checked_atlas()
    root = checked.root
    elements = root["elements"]
    records = root["trace"]["operation_qualification"]["records"]
    http_operations = [item for item in elements if item["interface"] == "http-operations"]
    qualified = {tuple(item["details"]["qualification_key"]): item for item in http_operations}

    assert len(records) == len(http_operations) == len(qualified) == 147
    assert not any(item["interface"] == "operation" for item in elements)
    assert root["counts"]["by_authority"]["riverhog"] == 364
    assert (
        sum(
            item["authority"] == "riverhog" and item["interface"] == "http-operations"
            for item in elements
        )
        == 109
    )
    assert (
        sum(
            item["authority"] == "riverhog" and item["interface"] == "http-schemas"
            for item in elements
        )
        == 253
    )
    assert len(root["projection"]["external_contract"]["http_route_supplements"]) == 2
    assert set(qualified) == {(item["application"], item["operation_id"]) for item in records}
    for record in records:
        item = qualified[(record["application"], record["operation_id"])]
        page = checked.files[item["dossier"]].decode()
        assert atlas._pretty_json(record) in page
        assert "### Structural operation bindings" in page
        assert "not executed qualification" in page


def test_collection_list_audit_exposes_scoped_tests_and_unestablished_progression() -> None:
    checked = checked_atlas()
    operation = next(
        item
        for item in checked.root["elements"]
        if item["interface"] == "http-operations"
        and item["authority"] == "riverhog"
        and item["details"]["operation_id"] == "list_collections"
    )
    page = checked.files[operation["dossier"]].decode()
    assert "### Progression evidence and open obligations" in page
    assert "riverhog-read-collection-progression/v1" in page
    sources = checked.files["riverhog-v1/evidence/sources.md"].decode()
    assert "no executed qualification result or CI attestation" in sources
    assert "Shared token codec" in sources
    assert "does not prove each route supplies those bindings correctly" in sources
    assert "uses a fake client and does not establish general output parity" in sources


def test_collection_list_has_a_readable_mutual_http_client_cli_audit_path() -> None:
    checked = checked_atlas()
    selected = [
        next(item for item in checked.root["elements"] if item["title"] == title)
        for title in (
            "GET /v1/collections",
            "riverhog_client.ApiClient.list_collections",
            "piggity collection list",
        )
    ]
    ids = {item["id"] for item in selected}
    for item, implementation in zip(
        selected,
        (
            collection_routes.list_collections,
            ApiClient.list_collections,
            piggity.main.collection_list_cmd,
        ),
        strict=True,
    ):
        assert ids - {item["id"]} <= set(item["related_element_ids"])
        page = checked.files[item["dossier"]].decode()
        source_links = {
            (
                (REPO_ROOT / "qualification/contracts" / item["dossier"])
                .parent.joinpath(unquote(target))
                .resolve(),
                int(line),
            )
            for target, line in re.findall(r"\]\(([^)]+)#L(\d+)\)", page)
        }
        definition = inspect.unwrap(implementation)
        assert (
            Path(inspect.getsourcefile(definition)),
            inspect.getsourcelines(definition)[1],
        ) in source_links
        for other in selected:
            if other is not item:
                assert f"]({navigation._relative_link(item['dossier'], other['dossier'])})" in page

    reading_path = (
        checked.files[selected[0]["dossier"]].decode().split("## Maintained corroboration", 1)[0]
    )
    parameter = next(line for line in reading_path.splitlines() if "`page_size` | query" in line)
    assert "| no | `25` |" in parameter
    assert "minimum=1; maximum=100" in parameter
    response = next(line for line in reading_path.splitlines() if "`200` |" in line)
    assert "application/json" in response
    assert (
        "[ListCollectionsResponse](../http-schemas/schemas-listcollectionsresponse.md)" in response
    )
    for status, code in (
        (400, "bad_request"),
        (401, "unauthorized"),
        (403, "forbidden"),
        (500, "internal_error"),
    ):
        response = next(line for line in reading_path.splitlines() if f"`{status}` |" in line)
        assert "[ErrorResponse](../http-schemas/schemas-errorresponse.md)" in response
        assert f"`{code}`" in response


@pytest.mark.parametrize("invalid_binding", ("missing-member", "export", "no-binding"))
def test_operation_client_binding_requires_a_python_member(invalid_binding: str) -> None:
    checked = checked_atlas()
    elements = deepcopy(checked.root["elements"])
    trace = deepcopy(checked.root["trace"])
    record = next(
        item
        for item in trace["operation_qualification"]["records"]
        if item["application"] == "riverhog" and item["operation_id"] == "list_collections"
    )
    if invalid_binding == "no-binding":
        record["client_bindings"] = []
    else:
        record["client_bindings"][0]["public_identity"] = (
            "example.Client.inherited_method"
            if invalid_binding == "missing-member"
            else "riverhog_client.ApiClient"
        )

    with pytest.raises(atlas.ContractAtlasError, match="lacks a Python"):
        discovery._link_operation_qualification(elements, trace, checked.root["projection"])


def test_inherited_client_method_routes_to_http_and_its_actual_definition() -> None:
    checked = checked_atlas()
    selected = [
        next(item for item in checked.root["elements"] if item["title"] == title)
        for title in (
            "GET /v1/collection-processing-claims",
            "riverhog_client.ApiClient.list_processing_claims",
        )
    ]
    http, client = selected
    assert client["details"]["unit"] == "member"
    assert client["details"]["owner"] == "riverhog_client.ApiClient"
    for item, other in ((http, client), (client, http)):
        assert other["id"] in item["related_element_ids"]
        page = checked.files[item["dossier"]].decode()
        assert f"]({navigation._relative_link(item['dossier'], other['dossier'])})" in page

    definition = inspect.unwrap(ApiClient.list_processing_claims)
    location = {
        "path": Path(inspect.getsourcefile(definition)).relative_to(REPO_ROOT).as_posix(),
        "line": inspect.getsourcelines(definition)[1],
    }
    label = f"{location['path']}::{definition.__qualname__}"
    assert navigation._repository_source_link(client["dossier"], location, label) in (
        checked.files[client["dossier"]].decode()
    )


@pytest.mark.parametrize("reverse", (False, True))
def test_operation_command_binding_uses_relative_paths_without_prefix_collisions(
    reverse: bool,
) -> None:
    projection = {
        "boundaries": {
            "components": [
                {
                    "distribution": "command-owner",
                    "path": "apps/command-owner",
                    "console_scripts": {"piggity": "different_import.cli:main"},
                },
                {
                    "distribution": "shared-callback",
                    "path": "packages/callback",
                    "console_scripts": {},
                },
            ]
        }
    }
    elements = [
        {
            "id": name,
            "interface": "cli",
            "authority": "command-owner",
            "details": {
                "command_path": path,
                "result_identity": name,
            },
        }
        for name, path in (
            ("short", ["piggity", "inspect"]),
            ("nested", ["piggity", "piggity", "inspect"]),
        )
    ]
    if reverse:
        elements.reverse()
    binding = {
        "command": "piggity inspect",
        "executable": "piggity",
        "result_identity": "nested",
        "source": {
            "path": "packages/callback/src/different_import/cli.py",
            "module": "different_import.cli",
            "symbol": "inspect_nested",
        },
    }
    assert discovery._cli_binding_element(binding, elements, projection)["id"] == "nested"
    binding["command"] = "inspect"
    binding["result_identity"] = "short"
    assert discovery._cli_binding_element(binding, elements, projection)["id"] == "short"
    binding["command"] = "extra inspect"
    with pytest.raises(atlas.ContractAtlasError, match="no unique executable command"):
        discovery._cli_binding_element(binding, elements, projection)
    binding["command"] = "inspect"
    elements.append(deepcopy(next(item for item in elements if item["id"] == "short")))
    with pytest.raises(atlas.ContractAtlasError, match="2 candidates"):
        discovery._cli_binding_element(binding, elements, projection)


def test_cli_discovery_retains_a_subcommand_named_like_its_parent() -> None:
    elements: list[dict[str, object]] = []
    discovery._walk_cli(
        elements,
        "owner",
        {
            "name": "tool",
            "commands": {
                "tool": {"name": "tool", "commands": {"inspect": {"name": "inspect"}}},
            },
        },
        "/external_contract/cli/tool",
        (),
        source_id="cli:tool",
    )
    assert [item["details"]["command_path"] for item in elements] == [
        ["tool"],
        ["tool", "tool"],
        ["tool", "tool", "inspect"],
    ]


def test_protocol_ownership_follows_the_declared_source_project() -> None:
    projection = deepcopy(checked_atlas().root["projection"])
    trace = deepcopy(checked_atlas().root["trace"])
    protocol = next(
        item for item in trace["sources"] if item["id"].startswith("protocol:generated:")
    )
    location = protocol["source"]
    expected = discovery._source_component(location, projection)
    # Another valid component name must not steal ownership through module spelling.
    location["module"] = "riverhog_client.schemas"
    assert discovery._source_component(location, projection) == expected
    owners = {
        item["authority"]
        for item in discovery._external_elements(projection, trace)
        if protocol["id"] in item["source_authority_ids"]
    }
    assert owners == {expected}
    component = next(
        item for item in projection["boundaries"]["components"] if item["distribution"] == expected
    )
    projection["boundaries"]["components"].append({**component, "distribution": "another-owner"})
    with pytest.raises(atlas.ContractAtlasError, match="ambiguous project ownership"):
        discovery._external_elements(projection, trace)
    location["path"] = "unowned/schema.py"
    with pytest.raises(atlas.ContractAtlasError, match="no declared project owner"):
        discovery._external_elements(projection, trace)


@pytest.mark.parametrize("change", ("missing", "duplicate", "unowned", "executable", "result"))
def test_operation_cli_bindings_fail_closed(change: str) -> None:
    checked = checked_atlas()
    trace = deepcopy(checked.root["trace"])
    record = next(
        item
        for item in trace["operation_qualification"]["records"]
        if item["application"] == "riverhog" and item["operation_id"] == "list_collections"
    )
    if change == "missing":
        record["cli_bindings"] = []
    elif change == "duplicate":
        record["cli_bindings"].append(deepcopy(record["cli_bindings"][0]))
    elif change == "unowned":
        record["cli_bindings"][0]["source"]["path"] = "unowned/cli.py"
    elif change == "executable":
        record["cli_bindings"][0]["executable"] = "unknown-executable"
    else:
        record["cli_bindings"][0]["result_identity"] = "wrong-result"
    with pytest.raises(
        atlas.ContractAtlasError, match="exact CLI bindings|no declared project owner|no unique"
    ):
        discovery._link_operation_qualification(
            deepcopy(checked.root["elements"]),
            trace,
            checked.root["projection"],
        )


def _linked_repository_paths(document: str, page: str) -> set[Path]:
    return {
        (REPO_ROOT / "qualification/contracts" / document)
        .parent.joinpath(unquote(target))
        .resolve()
        for target in re.findall(r"\]\(([^)#]+)(?:#[^)]*)?\)", page)
        if not target.startswith(("https:", "http:"))
    }


def test_source_records_and_fixtures_link_every_recorded_repository_location() -> None:
    checked = checked_atlas()
    document = "riverhog-v1/evidence/sources.md"
    page = checked.files[document].decode()
    for record in checked.root["sources"]:
        row = next(
            line
            for line in page.splitlines()
            if f'id="{atlas._source_anchor(record["id"])}"' in line
        )
        locations = [record["source"]] if "source" in record else []
        locations += record.get("bindings", []) + record.get("declarations", [])
        links = _linked_repository_paths(document, row)
        for location in locations:
            source = REPO_ROOT / location["path"]
            assert source in links, record["id"]
            assert source.is_file()
        for fixture in record.get("fixtures", []):
            assert REPO_ROOT / fixture["path"] in _linked_repository_paths(document, page)
    assert "do not record executed restart or introspection results" in page


@pytest.mark.parametrize(
    "interface",
    (
        "http-schemas",
        "configuration-environment",
        "configuration",
        "schema",
        "process-protocol",
        "durable-state",
        "python",
    ),
)
def test_non_operation_dossiers_have_direct_maintained_source_routes(interface: str) -> None:
    checked = checked_atlas()
    sources = {item["id"]: item for item in checked.root["sources"]}
    element = next(item for item in checked.root["elements"] if item["interface"] == interface)
    page = checked.files[element["dossier"]].decode()
    links = _linked_repository_paths(element["dossier"], page)
    for identity in element["source_authority_ids"]:
        record = sources[identity]
        locations = [record["source"]] if "source" in record else []
        locations += record.get("bindings", []) + record.get("declarations", [])
        assert locations
        assert all(REPO_ROOT / location["path"] in links for location in locations)
    if interface == "configuration-environment":
        assert "discovered source facts, not executed observations" in page


@pytest.mark.parametrize(
    "target",
    ("../../../tests/example.py#L8", "../../../tests/other.py#L7", "../../../tests/example.py"),
)
def test_repository_links_accept_only_trace_recorded_file_and_line(target: str) -> None:
    root = "riverhog-v1/index.md"
    allowed = {"../../tests/example.py#L7"}
    assert atlas._reachable_atlas_documents(
        root, {root: b"[test](../../../tests/example.py#L7)\n"}, repository_sources=allowed
    ) == {root}
    with pytest.raises(atlas.ContractAtlasError, match="unresolved local link"):
        atlas._reachable_atlas_documents(
            root, {root: f"[test]({target})\n".encode()}, repository_sources=allowed
        )


def test_file_source_routes_require_the_exact_recorded_path() -> None:
    root = "riverhog-v1/index.md"
    allowed = {"../../tests/example.py"}
    assert atlas._reachable_atlas_documents(
        root, {root: b"[source](../../../tests/example.py)\n"}, repository_sources=allowed
    ) == {root}
    for target in ("../../../tests/other.py", "../../../tests/example.py#L7"):
        with pytest.raises(atlas.ContractAtlasError, match="unresolved local link"):
            atlas._reachable_atlas_documents(
                root, {root: f"[source]({target})\n".encode()}, repository_sources=allowed
            )


def test_every_dossier_is_lossless_and_representative_contract_classes_are_semantics_first() -> (
    None
):
    checked = checked_atlas()
    elements = checked.root["elements"]
    projection = checked.root["projection"]

    for item in elements:
        page = checked.files[item["dossier"]].decode()
        assert page.index("## External contract") < page.index("## Evidence")
        assert "object (" not in page
        assert "array (" not in page
        for pointer in item["pointers"]:
            value = atlas.pointer_value(projection, pointer)
            exact = (
                f"<!-- exact-contract-value: {atlas.canonical_sha256(value)} -->\n\n"
                f"```json\n{atlas._pretty_json(value)}\n```"
            )
            assert exact in page

    representative_interfaces = {
        "http-operations",
        "cli",
        "configuration",
        "process-protocol",
        "process-protocol-operations",
        "process-protocol-schemas",
        "schema",
        "durable-state",
        "runtime-images",
    }
    representatives = {
        interface: next(item for item in elements if item["interface"] == interface)
        for interface in representative_interfaces
    }
    assert set(representatives) == representative_interfaces
    recovery = next(item for item in elements if "recovery-descriptor" in item["id"])
    for item in [*representatives.values(), recovery]:
        page = checked.files[item["dossier"]].decode()
        assert page.index("## External contract") < page.index("## Governing policies")
        assert page.index("## Governing policies") < page.index("## Evidence")


@pytest.mark.parametrize(
    "title,parameter,expected",
    [
        (
            "piggity collection list",
            "page_size",
            (
                "`--page-size`",
                "optional option; 1 value",
                "minimum=`1` (inclusive); maximum=`100` (inclusive)",
                "outside range: reject",
                "| `25`<br>Env: `null` |",
            ),
        ),
        (
            "piggity collection list",
            "json_mode",
            ("optional flag; 0 values", "boolean", "| `false`<br>Env: `null` |"),
        ),
        (
            "piggity collection list",
            "tag",
            ("collects repeats; maximum 100 occurrences", "not recorded"),
        ),
        (
            "piggity app key access list",
            "active",
            ("`--active`", "alternate: `--inactive`", "0 values"),
        ),
        (
            "gogurt listener install",
            "mounted_volume_provider",
            ('Env: `"GOGURT_MOUNTED_VOLUME_PROVIDER"`', "not recorded"),
        ),
        (
            "riverhog-ftp-adapter status",
            "page_size",
            ("optional option; 1 value", "| int | `25` |"),
        ),
        (
            "riverhog-recover",
            "output",
            ("optional positional; 0–1 values", "| Path | not recorded |"),
        ),
        ("stove0 preview", "inputs", ("required positional; 1+ values; no parser maximum",)),
        (
            "stove0 recipe validate",
            "path",
            (
                "existence required",
                "regular files allowed",
                "directories rejected",
                "access checks on existing paths: read",
                "resolve absolute path and symlinks: no",
                "dash uses normal path checks",
            ),
        ),
        (
            "stove0 preview",
            "intent",
            ("existence required", "directories rejected", "access checks on existing paths: read"),
        ),
        (
            "gogurt list",
            "config",
            (
                "existence not required",
                "directories allowed",
                "access checks on existing paths: read",
            ),
        ),
        (
            "riverhog-storage-adapter-filesystem-materialize",
            "path",
            ("collects repeats; no declared occurrence maximum", "| `[]` |"),
        ),
    ],
)
def test_cli_primary_reading_path_exposes_parameter_semantics(
    title: str, parameter: str, expected: tuple[str, ...]
) -> None:
    checked = checked_atlas()
    element = next(item for item in checked.root["elements"] if item["title"] == title)
    page = checked.files[element["dossier"]].decode().split("## Maintained corroboration", 1)[0]
    row = next(line for line in page.splitlines() if f"</a>`{parameter}`" in line)
    assert all(fragment in row for fragment in expected), row
    assert "{'class':" not in row


@pytest.mark.parametrize(
    ("title", "expected"),
    [
        (
            "riverhog-recover",
            (
                "Unique long-option abbreviations: accepted.",
                "### Argument combinations",
                "At most one of:",
                "[`--description-only`](#",
                "[`--tags-only`](#",
            ),
        ),
        ("riverhog-api", ("Subcommand selection: optional.",)),
        ("stove0-server", ("Subcommand selection: required.",)),
        (
            "stove0",
            (
                "Subcommand selection: required.",
                "Extra arguments at this parser: accepted. "
                "Subcommand selection and child parsing still apply.",
                "Options after positional arguments at this parser: left as arguments.",
                "Unknown options at this parser: rejected.",
            ),
        ),
        (
            "stove0 recipe validate",
            (
                "Extra arguments at this parser: rejected.",
                "Options after positional arguments at this parser: parsed as options.",
                "Unknown options at this parser: rejected.",
            ),
        ),
    ],
)
def test_cli_primary_reading_path_exposes_command_rules(
    title: str, expected: tuple[str, ...]
) -> None:
    checked = checked_atlas()
    element = next(
        item
        for item in checked.root["elements"]
        if item["interface"] == "cli" and item["title"] == title
    )
    page = checked.files[element["dossier"]].decode().split("## Maintained corroboration", 1)[0]
    assert all(fragment in page for fragment in expected), page


@pytest.mark.parametrize("default", [False, 0, "", [], None])
def test_cli_renderer_preserves_recorded_defaults_and_choices(default: object) -> None:
    pointer = "/external_contract/cli/probe/parameters"
    parameter = {
        "name": "value",
        "kind": "TyperOption",
        "options": ["--value", "-v"],
        "default": default,
        "type": {"name": "choice", "choices": ["a", "b"]},
    }
    projection = {
        "external_contract": {
            "extents": {
                "decisions": [
                    {
                        "source_pointer": f"{pointer}/0",
                        "unit": "values-per-occurrence",
                        "minimum": 1,
                        "maximum": 1,
                    },
                ]
            }
        }
    }

    def render() -> str:
        return "\n".join(
            dossier_rendering._render_cli(
                [pointer],
                [[parameter]],
                set(),
                element={},
                path="probe.md",
                projection=projection,
                elements_by_id={},
            )
        )

    row = next(line for line in render().splitlines() if "</a>`value`" in line)
    assert f"| `{dossier_rendering._compact_json(default)}` |" in row
    assert 'choice; choices=`["a","b"]`' in row
    assert "`--value`, `-v`" in row
    del parameter["default"]
    row = next(line for line in render().splitlines() if "</a>`value`" in line)
    assert row.endswith("| not recorded |")


def test_cli_authority_resolution_fails_closed() -> None:
    checked = checked_atlas()
    projection = checked.root["projection"]
    elements = {item["id"]: item for item in checked.root["elements"]}
    command = next(
        item
        for item in elements.values()
        if item["interface"] == "cli" and item["title"] == "piggity collection list"
    )
    result_pointer = next(
        pointer for pointer in command["pointers"] if pointer.endswith("/result_contract")
    )
    result = atlas.pointer_value(projection, result_pointer)
    authority = result["success"][0]["stdout"]["json"]
    kwargs = {
        "element": command,
        "pointer": f"{result_pointer}/success/0/stdout",
        "path": command["dossier"],
        "projection": projection,
        "elements_by_id": elements,
    }

    with pytest.raises(atlas.ContractAtlasError, match="no atlas resolver"):
        atlas._cli_authority_reference({"kind": "unknown"}, **kwargs)

    inapplicable = {**authority, "method": "POST"}
    with pytest.raises(atlas.ContractAtlasError, match="resolves to 0"):
        atlas._cli_authority_reference(inapplicable, **kwargs)

    target = next(
        item
        for item in elements.values()
        if item["interface"] == "http-operations"
        and item.get("details", {}).get("operation_id") == "list_collections"
    )
    ambiguous = {**elements, "duplicate-for-test": {**target, "id": "duplicate-for-test"}}
    with pytest.raises(atlas.ContractAtlasError, match="resolves to 2"):
        atlas._cli_authority_reference(authority, **{**kwargs, "elements_by_id": ambiguous})


def test_every_extent_fact_names_and_links_its_exact_subject() -> None:
    checked = checked_atlas()
    decisions = {
        item["id"]: item
        for item in checked.root["projection"]["external_contract"]["extents"]["decisions"]
    }

    for element in checked.root["elements"]:
        decision_ids = element["extent_decision_ids"]
        if not decision_ids:
            continue
        page = checked.files[element["dossier"]].decode()
        section = page.split("### Progression, limits, and lifecycle\n", 1)[1].split(
            "\n## Governing policies", 1
        )[0]
        rows = [
            line
            for line in section.splitlines()
            if line.startswith("| ")
            and not line.startswith("| Applies to ")
            and not line.startswith("|---")
        ]

        assert "| Applies to | Contract | Bounds or reason |" in section
        assert len(rows) == len(decision_ids)
        assert all("](#" in row for row in rows)
        for pointer in {decisions[identity]["source_pointer"] for identity in decision_ids}:
            anchor = atlas._subject_anchor(pointer)
            assert page.count(f'id="{anchor}"') == 1
            assert f"](#{anchor})" in section or (f'id="{anchor}"' in section and "](#" in section)

        if element["interface"].startswith("http-"):
            assert not re.search(r"\bparameter \d+\b", section)


def test_atlas_rejects_broken_fragments_and_duplicate_explicit_anchors() -> None:
    with pytest.raises(atlas.ContractAtlasError, match="unresolved local anchor"):
        atlas._reachable_atlas_documents(
            "index.md",
            {
                "index.md": b"[detail](detail.md#missing)\n",
                "detail.md": b"# Detail\n",
            },
        )

    with pytest.raises(atlas.ContractAtlasError, match="repeats a stable local anchor"):
        atlas._reachable_atlas_documents(
            "index.md",
            {"index.md": b'<a id="subject"></a>\n<a id="subject"></a>\n'},
        )


def _primary_contract(authority: str, title: str) -> tuple[dict[str, Any], str]:
    checked = checked_atlas()
    element = next(
        item
        for item in checked.root["elements"]
        if item["authority"] == authority and item["title"] == title
    )
    page = checked.files[element["dossier"]].decode()
    return element, page.split("## Governing policies", 1)[0].split(
        "## Maintained corroboration", 1
    )[0]


@pytest.mark.parametrize(
    ("authority", "title", "facts"),
    [
        ("riverhog", "schemas: ArchiveStoreName", ('`pattern`: `"^[a-z0-9]+(?:-[a-z0-9]+)*$"`',)),
        (
            "riverhog",
            "schemas: CreateOrResumeCollectionUploadSessionOut",
            (
                "`additionalProperties`: `false`",
                "All must match (`allOf`)",
                "If schema matches | Then must match | Otherwise must match",
                'properties={state: (const="finalized")}',
                'properties={archive_root_sha256: (type="string")',
                '"propertyName":"state"',
            ),
        ),
        (
            "stove0-recipe-config",
            "stove0-recipe-config:configuration:recipe-catalog configuration",
            (
                "definition `RecipeDefinition`",
                '`allow_derived_inputs` | no | type="boolean"; default=false',
                '`retirement_grace_seconds` | no | type="integer"; minimum=0; default=0',
                '`revision` | yes | type="integer"; minimum=1',
                "`additionalProperties`: `false`",
                '"propertyName":"kind"',
                "definition `JsonValue`",
                "Accepts: any JSON value.",
            ),
        ),
        (
            "stove0-target-support",
            "generated:stove0-target: TargetConformanceResult",
            (
                "definition `AcceptedTargetJob`",
                "`additionalProperties`: `false`",
                '`request_sha256` | yes | type="string"; pattern="^[0-9a-f]{64}$"',
                "definition `JsonValue`",
                "Accepts: any JSON value.",
            ),
        ),
        ("stove0", "schemas: JsonValue", ("Accepts: any JSON value.",)),
        (
            "riverhog-ftp-adapter",
            "securitySchemes: RiverhogFtpAdapterBearer",
            ('`scheme` | `"bearer"`', '`type` | `"http"`'),
        ),
        (
            "riverhog-storage-adapter-support",
            "generated:riverhog-storage-adapter protocol",
            (
                '`compatibility · provider_ontology` | `"private"`',
                '`compatibility · unknown_fields` | `"reject"`',
            ),
        ),
        (
            "riverhog-server",
            "RIVERHOG_ARCHIVE_STORE_{store}_{setting}",
            ('`parameters · store · normalization` | `"uppercase-dashes-to-underscores"`',),
        ),
        (
            "riverhog-ftp-custody",
            "riverhog-ftp-custody: operational-database",
            (
                "### Table: `claims`",
                "### Table: `adapter_state`",
                "### Table: `completion_events`",
                "### Table: `completion_failures`",
                "`key` | `TEXT` | yes",
                "`event_id` | `TEXT` | yes",
                "`claim_id` | `TEXT` | no",
                '"checks":["(claim_bytes >= 0)"]',
            ),
        ),
        (
            "riverhog-ftp-custody",
            "riverhog-ftp-custody: completion-log",
            (
                "### Record schema",
                '`event_id` | yes | type="string"; minLength=1',
                "`additionalProperties`: `false`",
            ),
        ),
        (
            "gogurt",
            "gogurt list",
            (
                "### Local structured outputs",
                "`gogurt-cli-error/v1`",
                '`code` | yes | enum=["config_error","listener_error"]',
                '`message` | yes | type="string"',
            ),
        ),
        (
            "riverhog-recover",
            "riverhog-recover",
            (
                "### Local structured outputs",
                '`framing` | `"newline-delimited-json"`',
                '`sequence · start` | `"authority"`',
                '`sequence · repeated` | `"tag"`',
                '`sequence · end` | `"complete"`',
                "##### Record `authority`",
                "##### Record `complete`",
                '`tag_count` | yes | type="integer"; minimum=0',
            ),
        ),
        (
            "stove0-review-planning",
            "stove0-review-planning",
            (
                "### Local structured outputs",
                '`status` | `"conformant"`',
                "`observer_contract · maximum_result_bytes` | `262144`",
                "`operation_contract · source_retirement_permitted` | `false`",
            ),
        ),
    ],
)
def test_primary_dossiers_expose_declared_semantics(
    authority: str, title: str, facts: tuple[str, ...]
) -> None:
    _element, primary = _primary_contract(authority, title)
    assert all(fact in primary for fact in facts), [fact for fact in facts if fact not in primary]
    assert "additional keys=" not in primary
    assert "```json" not in primary


def test_http_response_headers_are_readable_with_their_status_and_constraints() -> None:
    checked = checked_atlas()
    element = next(
        item
        for item in checked.root["elements"]
        if item["interface"] == "http-operations"
        and item["details"].get("path")
        == "/v1/collections/{collection_id}/provenance/journals/{journal_id}"
    )
    primary = checked.files[element["dossier"]].decode().split("### Exact owned JSON", 1)[0]
    headers = primary.split("#### Response headers", 1)[1].split("### Progression", 1)[0]
    for status, name in (
        ("200", "Accept-Ranges"),
        ("200", "Content-Length"),
        ("200", "ETag"),
        ("206", "Accept-Ranges"),
        ("206", "Content-Length"),
        ("206", "Content-Range"),
        ("206", "ETag"),
    ):
        row = next(
            line
            for line in headers.splitlines()
            if f"| `{status}` |" in line and f"`{name}` |" in line
        )
        assert "| yes |" in row
        if status == "200" and name == "Accept-Ranges":
            assert 'const="bytes"' in row
        if status == "200" and name == "Content-Length":
            assert "minimum=0" in row
        if status == "200" and name == "ETag":
            assert "pattern=" in row and "[0-9a-f]{64}" in row


def test_nested_definition_links_resolve_to_primary_constraints() -> None:
    element, primary = _primary_contract(
        "stove0-recipe-config", "stove0-recipe-config:configuration:recipe-catalog configuration"
    )
    definition = f"{element['pointers'][0]}/$defs/RecipeDefinition"
    anchor = navigation._subject_anchor(definition)
    assert f"[RecipeDefinition](#{anchor})" in primary
    section = primary.split(f'id="{anchor}"', 1)[1].split("\n### ", 1)[0]
    assert '`allow_derived_inputs` | no | type="boolean"; default=false' in section
    assert '`revision` | yes | type="integer"; minimum=1' in section


def test_large_integer_bounds_are_numeric_in_primary_content_and_exact_in_fallback() -> None:
    checked = checked_atlas()
    element, primary = _primary_contract(
        "riverhog-provenance", "Riverhog provenance v1 journal entry"
    )
    pointer = f"{element['pointers'][0]}/properties/sequence/maximum"
    assert pointer in checked.root["projection_unsafe_integer_paths"]
    encoded = atlas.pointer_value(checked.root["projection"], pointer)
    assert encoded == "9223372036854775807"
    assert atlas.pointer_value(atlas.reassemble_projection(checked), pointer) == 9223372036854775807
    row = next(line for line in primary.splitlines() if "</a>`sequence`" in line)
    assert "maximum=9223372036854775807" in row
    assert 'maximum="9223372036854775807"' not in row
    fallback = checked.files[element["dossier"]].decode().split("### Exact owned JSON", 1)[1]
    assert '"maximum": "9223372036854775807"' in fallback
    assert "projection_unsafe_integer_paths" in fallback


@pytest.mark.parametrize("default", [False, 0, "", [], {}, None])
def test_schema_defaults_are_literal_values_including_empty_objects(default: object) -> None:
    primary = "\n".join(
        dossier_rendering._render_schema(
            {"type": "object", "properties": {"value": {"default": default}}}, "/schema", set()
        )
    )
    row = next(line for line in primary.splitlines() if "</a>`value`" in line)
    assert f"default={dossier_rendering._compact_json(default)}" in row
    assert "any JSON value" not in row


@pytest.mark.parametrize(
    ("schema", "meaning"),
    [({}, "any JSON value"), (True, "any JSON value"), (False, "no JSON value")],
)
def test_unrestricted_and_boolean_schemas_have_accurate_meanings(
    schema: object, meaning: str
) -> None:
    assert f"Accepts: {meaning}." in "\n".join(
        dossier_rendering._render_schema(schema, "/schema", set())
    )


def test_exact_json_is_collapsed_without_hiding_primary_contract_facts() -> None:
    checked = checked_atlas()
    for element in checked.root["elements"]:
        page = checked.files[element["dossier"]].decode()
        primary, exact = page.split("### Exact owned JSON", 1)
        assert "<details>" not in primary.split("## Evidence", 1)[0]
        assert exact.startswith(
            "\n\n<details>\n<summary>Expand exact machine-owned values</summary>\n"
        )
        assert "</details>" in exact


def _http_primary(value: dict[str, Any], element: dict[str, Any]) -> str:
    return "\n".join(
        dossier_rendering._render_http(
            value,
            element["details"],
            element["pointers"][0],
            set(),
            element=element,
            elements_by_id={item["id"]: item for item in checked_atlas().root["elements"]},
        )
    )


def test_every_http_permission_formula_and_parameter_description_is_primary() -> None:
    checked = checked_atlas()
    formulas = descriptions = 0
    for element in checked.root["elements"]:
        if element["interface"] != "http-operations" or element["details"].get("supplemental"):
            continue
        value = atlas.pointer_value(checked.root["projection"], element["pointers"][0])
        primary = checked.files[element["dossier"]].decode().split("### Progression", 1)[0]
        if "x-riverhog-permission-requirements" in value:
            formula = value["x-riverhog-permission-requirements"]
            assert (
                "`x-riverhog-permission-requirements`: "
                f"`{dossier_rendering._compact_json(formula)}`" in primary
            )
            changed = deepcopy(value)
            changed["x-riverhog-permission-requirements"] = [{"any_of": ["mutation:permission"]}]
            rendered = _http_primary(changed, element)
            assert '"mutation:permission"' in rendered
            assert rendered != _http_primary(value, element)
            formulas += 1
        for parameter in value.get("parameters", []):
            if "description" in parameter:
                row = next(
                    line for line in primary.splitlines() if f"`{parameter['name']}` |" in line
                )
                assert parameter["description"] in row
                descriptions += 1
    assert formulas == 105
    assert descriptions == 2


def test_current_http_field_shapes_cannot_drop_value_changes() -> None:
    """Inventory current HTTP input shapes independently of renderer handled-key sets.

    One value per structural path and scalar type bounds the mutation suite. The
    guard checks visible changed values, not self-reported renderer coverage.
    """
    samples: dict[
        tuple[tuple[str, ...], type], tuple[dict[str, Any], dict[str, Any], list[Any]]
    ] = {}

    def visit(
        value: Any,
        path: list[Any],
        shape: tuple[str, ...],
        element: dict[str, Any],
        root: dict[str, Any],
    ) -> None:
        if isinstance(value, dict) and value:
            for key, child in value.items():
                # Status, media type, property and header names are data, not renderer branches.
                label = (
                    "*"
                    if path and path[-1] in {"responses", "content", "properties", "headers"}
                    else key
                )
                visit(child, [*path, key], (*shape, label), element, root)
        elif isinstance(value, list) and value:
            for index, child in enumerate(value):
                visit(child, [*path, index], (*shape, "*"), element, root)
        else:
            samples.setdefault((shape, type(value)), (element, root, path))

    checked = checked_atlas()
    for element in checked.root["elements"]:
        if element["interface"] == "http-operations" and not element["details"].get("supplemental"):
            value = atlas.pointer_value(checked.root["projection"], element["pointers"][0])
            visit(value, [], (), element, value)
    assert len(samples) > 30
    for (_shape, _type), (element, value, path) in samples.items():
        changed = deepcopy(value)
        parent = changed
        for key in path[:-1]:
            parent = parent[key]
        original = parent[path[-1]]
        if path[-1] == "$ref":
            parent[path[-1]] = "#/components/schemas/missing-for-fidelity-test"
            with pytest.raises(atlas.ContractAtlasError, match="unresolved local schema reference"):
                _http_primary(changed, element)
            continue
        mutation = not original if isinstance(original, bool) else "fidelity-mutation-885"
        parent[path[-1]] = mutation
        after = _http_primary(changed, element)
        assert after != _http_primary(value, element), path
        if not isinstance(original, bool):
            assert mutation in after, path


@pytest.mark.parametrize("extra", [False, None, 0, "", [], {}, {"all_of": [{"any_of": []}]}])
def test_http_unknown_fields_survive_at_every_record_level(extra: object) -> None:
    element, _ = _primary_contract("riverhog", "GET /v1/collections")
    value = {
        "parameters": [{"name": "x", "schema": {}, "future_parameter": extra}],
        "requestBody": {
            "future_body": extra,
            "content": {"application/json": {"schema": {}, "future_request_media": extra}},
        },
        "responses": {
            "200": {
                "future_response": extra,
                "content": {"application/json": {"schema": {}, "future_response_media": extra}},
                "headers": {"X-Probe": {"schema": {}, "future_header": extra}},
            }
        },
        "future_operation": extra,
    }
    primary = _http_primary(value, element)
    for key in (
        "future_parameter",
        "future_body",
        "future_request_media",
        "future_response",
        "future_response_media",
        "future_header",
        "future_operation",
    ):
        assert f"`{key}`: `{dossier_rendering._compact_json(extra)}`" in primary


def test_schema_references_are_scoped_actionable_and_keep_use_site_constraints() -> None:
    checked = checked_atlas()
    element, primary = _primary_contract("riverhog", "schemas: ListCollectionsResponse")
    fields = primary.split("### Fields", 1)[1].split("### Progression", 1)[0]
    assert "[CollectionSummaryOut](schemas-collectionsummaryout.md)" in fields
    assert "#/components/schemas/CollectionSummaryOut" not in fields
    owners = {item["id"]: item for item in checked.root["elements"]}
    foreign = next(
        item
        for item in owners.values()
        if item["authority"] == "stove0" and item["interface"] == "http-schemas"
    )
    foreign = {
        **foreign,
        "pointers": [
            "/external_contract/http_openapi/stove0/components/schemas/CollectionSummaryOut"
        ],
    }
    owners[foreign["id"]] = foreign
    schema = {
        "$ref": "#/components/schemas/CollectionSummaryOut",
        "minProperties": 1,
        "future_rule": False,
    }
    output = "\n".join(
        dossier_rendering._render_schema(
            schema, element["pointers"][0], set(), element=element, elements_by_id=owners
        )
    )
    assert "[CollectionSummaryOut](schemas-collectionsummaryout.md)" in output
    assert "`minProperties`: `1`" in output and "`future_rule`: `false`" in output
    local_owner = next(
        item
        for item in owners.values()
        if item["authority"] == "riverhog" and item["title"] == "schemas: CollectionSummaryOut"
    )
    del owners[local_owner["id"]]
    with pytest.raises(atlas.ContractAtlasError, match="unresolved local schema reference"):
        dossier_rendering._render_schema(
            schema, element["pointers"][0], set(), element=element, elements_by_id=owners
        )


def test_recursive_schema_links_do_not_rewrite_literal_reference_shaped_values() -> None:
    schema = {
        "$defs": {"A/B": {"type": "object", "properties": {"child": {"$ref": "#/$defs/A~1B"}}}},
        "properties": {
            "root": {"$ref": "#/$defs/A~1B", "default": {"$ref": "#/$defs/missing-literal"}}
        },
    }
    primary = "\n".join(dossier_rendering._render_schema(schema, "/schema", set()))
    link = f"[A/B](#{navigation._subject_anchor('/schema/$defs/A~1B')})"
    assert primary.count(link) == 3  # definition inventory, root field, recursive child
    assert 'default={"$ref":"#/$defs/missing-literal"}' in primary
    schema["properties"]["root"]["$ref"] = "#/$defs/missing"
    with pytest.raises(atlas.ContractAtlasError):
        dossier_rendering._render_schema(schema, "/schema", set())


def test_current_nullable_cli_authority_modifier_is_primary() -> None:
    checked = checked_atlas()
    found = []
    for element in checked.root["elements"]:
        if element["interface"] != "cli":
            continue
        for pointer in element["pointers"]:
            if not pointer.endswith("/result_contract"):
                continue
            result = atlas.pointer_value(checked.root["projection"], pointer)
            for outcome in result["success"] + result["failures"]:
                for channel in ("stdout", "stderr"):
                    for semantics in outcome[channel].values():
                        if isinstance(semantics, dict) and "nullable" in semantics:
                            found.append(semantics)
                            primary = (
                                checked.files[element["dossier"]]
                                .decode()
                                .split("### Exact owned JSON", 1)[0]
                            )
                            assert "`nullable`: `true`" in primary
    assert len(found) == 1


@pytest.mark.parametrize("extra", [False, None, 0, "", [], {}])
def test_specialized_python_and_state_records_preserve_extra_fields(extra: object) -> None:
    literal = dossier_rendering._compact_json(extra)
    python_value = {
        "future_python": extra,
        "contract": {
            "kind": "dataclass",
            "future_contract": extra,
            "fields": [{"name": "value", "type": "str", "default": "none", "future_field": extra}],
        },
    }
    primary = "\n".join(dossier_rendering._render_python(python_value, "/python", set()))
    for key in ("future_python", "future_contract", "future_field"):
        assert f"`{key}`: `{literal}`" in primary
    table = {
        "name": "rows",
        "future_table": extra,
        "columns": [{"name": "value", "type": "TEXT", "nullable": False, "future_column": extra}],
        "constraints": [
            {"kind": "check", "definition": "CHECK (value != '')", "future_constraint": extra}
        ],
    }
    primary = "\n".join(dossier_rendering._render_relational_table(table, "/table", set()))
    assert f'"future_column":{literal}' in primary
    for key in ("future_table", "future_constraint"):
        assert f"`{key}`: `{literal}`" in primary
    document = {"id": "config", "schema": {}, "future_document": extra}
    primary = "\n".join(
        dossier_rendering._render_durable_state(
            ["/document"], [document], {"state_unit": "json-document"}, set()
        )
    )
    assert f"`future_document`: `{literal}`" in primary


def test_current_cli_record_shapes_keep_unknown_modifiers_at_use() -> None:
    checked = checked_atlas()
    elements = {item["id"]: item for item in checked.root["elements"]}
    samples: dict[tuple[str, frozenset[str]], tuple[dict[str, Any], list[Any], list[Any]]] = {}

    def visit(
        value: Any, path: list[Any], context: str, element: dict[str, Any], values: list[Any]
    ) -> None:
        if isinstance(value, dict):
            samples.setdefault((context, frozenset(value)), (element, values, path))
            for key, child in value.items():
                # Linked definitions are checked against their canonical target; schemas
                # and literal values have dedicated mutation tests below.
                if key not in {
                    "schema",
                    "definition",
                    "document",
                    "records",
                    "trigger",
                    "selected_by",
                    "exit_status",
                }:
                    visit(child, [*path, key], key, element, values)
        elif isinstance(value, list):
            for index, child in enumerate(value):
                visit(child, [*path, index], context, element, values)

    for element in elements.values():
        if element["interface"] != "cli":
            continue
        values = [atlas.pointer_value(checked.root["projection"], p) for p in element["pointers"]]
        for index, (pointer, value) in enumerate(zip(element["pointers"], values, strict=True)):
            visit(value, [index], pointer.rsplit("/", 1)[-1], element, values)
    assert len(samples) > 20
    for shape, (element, values, path) in samples.items():
        changed = deepcopy(values)
        record = changed
        for key in path:
            record = record[key]
        record["future-fidelity-rule"] = "cli-fidelity-mutation-885"
        try:
            primary = "\n".join(
                dossier_rendering._render_cli(
                    element["pointers"],
                    changed,
                    set(),
                    element=element,
                    path=element["dossier"],
                    projection=checked.root["projection"],
                    elements_by_id=elements,
                )
            )
        except atlas.ContractAtlasError as exc:
            # Channel dictionaries are keyed by output mode. A new structured
            # mode must resolve an authority, or fail rather than disappear.
            assert shape[0] in {"stdout", "stderr"} and "no atlas resolver" in str(exc), shape
        else:
            assert "future-fidelity-rule" in primary and "cli-fidelity-mutation-885" in primary, (
                shape
            )


@pytest.mark.parametrize("keyword", ["allOf", "anyOf", "oneOf", "prefixItems"])
def test_schema_combinators_preserve_operator_order_and_empty_structures(keyword: str) -> None:
    variants = [False, {"const": None}, {"const": 0}, {"const": []}, {"const": {}}, True]

    def render(value: object) -> str:
        return "\n".join(dossier_rendering._render_schema({keyword: value}, "/schema", set()))

    primary = render(variants)
    assert f"(`{keyword}`)" in primary
    for fact in (
        "no JSON value",
        "const=null",
        "const=0",
        "const=[]",
        "const={}",
        "any JSON value",
    ):
        assert fact in primary
    assert primary != render(list(reversed(variants)))
    assert render([]) != "\n".join(dossier_rendering._render_schema({}, "/schema", set()))


def test_current_schema_keyword_shapes_preserve_changed_literals() -> None:
    checked = checked_atlas()
    # Inventory actual schema nodes from standalone schemas and validated Python models.
    samples: dict[tuple[str, type], tuple[dict[str, Any], str]] = {}

    def visit(schema: Any) -> None:
        if not isinstance(schema, dict):
            return
        for key, value in schema.items():
            if key in {
                "properties",
                "$defs",
                "definitions",
                "patternProperties",
                "dependentSchemas",
            } and isinstance(value, dict):
                for child in value.values():
                    visit(child)
            elif key in {"allOf", "anyOf", "oneOf", "prefixItems"} and isinstance(value, list):
                for child in value:
                    visit(child)
            elif key in {
                "items",
                "additionalProperties",
                "if",
                "then",
                "else",
                "not",
            } and isinstance(value, dict):
                visit(value)
            elif key != "$ref":
                samples.setdefault((key, type(value)), (schema, key))

    for element in checked.root["elements"]:
        for pointer in element["pointers"]:
            value = atlas.pointer_value(checked.root["projection"], pointer)
            if element["interface"] in {"http-schemas", "schema", "process-protocol-schemas"}:
                visit(value)
            elif element["interface"] == "python":
                visit(value["contract"].get("schema"))
    assert len(samples) > 20
    for shape, (_schema, key) in samples.items():
        # Isolate the factual keyword to test both root and inline-field paths.
        # Ref resolution and combinator structure have separate adversarial tests.
        changed = {key: "schema-fidelity-mutation-885"}
        for value in (changed, {"properties": {"probe": changed}}):
            primary = "\n".join(dossier_rendering._render_schema(value, "/schema", set()))
            assert "schema-fidelity-mutation-885" in primary, shape


@pytest.mark.parametrize("value", [False, None, 0, "", [], {}, "False", "None", "0", "[]", "{}"])
def test_literal_record_renderers_preserve_json_type_and_empty_values(value: object) -> None:
    expected = f"`{dossier_rendering._compact_json(value)}`"
    record = {"recorded_value": value}
    for lines in (
        dossier_rendering._render_generic(["/record"], [record], set()),
        dossier_rendering._render_operation(record, "/record", set()),
    ):
        assert f"`recorded_value` | {expected} |" in "\n".join(lines)


@pytest.mark.parametrize(
    "keyword", ["properties", "$defs", "allOf", "anyOf", "oneOf", "prefixItems"]
)
def test_schema_specialization_rejects_unhandled_structural_types(keyword: str) -> None:
    with pytest.raises(atlas.ContractAtlasError, match="invalid schema structure"):
        dossier_rendering._render_schema({keyword: None}, "/schema", set())
